/**
 * @file tt
 * @module docmark-util-symbol/tt
 */

/**
 * Registry all token types exposed by docmark.
 *
 * @enum {string}
 */
const tt = {
  atxHeading: 'atxHeading',
  atxHeadingSequence: 'atxHeadingSequence',
  atxHeadingText: 'atxHeadingText',
  autolink: 'autolink',
  autolinkEmail: 'autolinkEmail',
  autolinkMarker: 'autolinkMarker',
  autolinkProtocol: 'autolinkProtocol',
  blockQuote: 'blockQuote',
  blockQuoteMarker: 'blockQuoteMarker',
  blockQuotePrefix: 'blockQuotePrefix',
  blockQuotePrefixWhitespace: 'blockQuotePrefixWhitespace',
  blockTag: 'blockTag',
  blockTagContent: 'blockTagContent',
  characterEscape: 'characterEscape',
  characterEscapeValue: 'characterEscapeValue',
  characterReference: 'characterReference',
  characterReferenceMarker: 'characterReferenceMarker',
  characterReferenceMarkerHexadecimal: 'characterReferenceMarkerHexadecimal',
  characterReferenceMarkerNumeric: 'characterReferenceMarkerNumeric',
  characterReferenceValue: 'characterReferenceValue',
  chunkComment: 'chunkComment',
  chunkContent: 'chunkContent',
  chunkDocument: 'chunkDocument',
  chunkFlow: 'chunkFlow',
  chunkMarkdown: 'chunkMarkdown',
  chunkString: 'chunkString',
  chunkText: 'chunkText',
  codeFenced: 'codeFenced',
  codeFencedFence: 'codeFencedFence',
  codeFencedFenceInfo: 'codeFencedFenceInfo',
  codeFencedFenceMeta: 'codeFencedFenceMeta',
  codeFencedFenceSequence: 'codeFencedFenceSequence',
  codeFlowValue: 'codeFlowValue',
  codeIndented: 'codeIndented',
  codeText: 'codeText',
  codeTextData: 'codeTextData',
  codeTextPadding: 'codeTextPadding',
  codeTextSequence: 'codeTextSequence',
  comment: 'comment',
  commentCloser: 'commentCloser',
  commentLineMarker: 'commentLineMarker',
  commentLinePadding: 'commentLinePadding',
  commentLinePrefix: 'commentLinePrefix',
  commentOpener: 'commentOpener',
  content: 'content',
  data: 'data',
  definition: 'definition',
  definitionDestination: 'definitionDestination',
  definitionDestinationLiteral: 'definitionDestinationLiteral',
  definitionDestinationLiteralMarker: 'definitionDestinationLiteralMarker',
  definitionDestinationRaw: 'definitionDestinationRaw',
  definitionDestinationString: 'definitionDestinationString',
  definitionLabel: 'definitionLabel',
  definitionLabelMarker: 'definitionLabelMarker',
  definitionLabelString: 'definitionLabelString',
  definitionMarker: 'definitionMarker',
  definitionTitle: 'definitionTitle',
  definitionTitleMarker: 'definitionTitleMarker',
  definitionTitleString: 'definitionTitleString',
  emphasis: 'emphasis',
  emphasisSequence: 'emphasisSequence',
  emphasisText: 'emphasisText',
  eoc: 'eoc',
  escapeMarker: 'escapeMarker',
  hardBreakEscape: 'hardBreakEscape',
  hardBreakTrailing: 'hardBreakTrailing',
  htmlFlow: 'htmlFlow',
  htmlFlowData: 'htmlFlowData',
  htmlText: 'htmlText',
  htmlTextData: 'htmlTextData',
  image: 'image',
  inlineTag: 'inlineTag',
  inlineTagText: 'inlineTagText',
  label: 'label',
  labelEnd: 'labelEnd',
  labelImage: 'labelImage',
  labelImageMarker: 'labelImageMarker',
  labelLink: 'labelLink',
  labelMarker: 'labelMarker',
  labelText: 'labelText',
  lineEnding: 'lineEnding',
  lineEndingBlank: 'lineEndingBlank',
  linePrefix: 'linePrefix',
  lineSuffix: 'lineSuffix',
  link: 'link',
  listItemIndent: 'listItemIndent',
  listItemMarker: 'listItemMarker',
  listItemPrefix: 'listItemPrefix',
  listItemPrefixWhitespace: 'listItemPrefixWhitespace',
  listItemValue: 'listItemValue',
  listOrdered: 'listOrdered',
  listUnordered: 'listUnordered',
  paragraph: 'paragraph',
  reference: 'reference',
  referenceMarker: 'referenceMarker',
  referenceString: 'referenceString',
  resource: 'resource',
  resourceDestination: 'resourceDestination',
  resourceDestinationLiteral: 'resourceDestinationLiteral',
  resourceDestinationLiteralMarker: 'resourceDestinationLiteralMarker',
  resourceDestinationRaw: 'resourceDestinationRaw',
  resourceDestinationString: 'resourceDestinationString',
  resourceMarker: 'resourceMarker',
  resourceTitle: 'resourceTitle',
  resourceTitleMarker: 'resourceTitleMarker',
  resourceTitleString: 'resourceTitleString',
  setextHeading: 'setextHeading',
  setextHeadingLine: 'setextHeadingLine',
  setextHeadingLineSequence: 'setextHeadingLineSequence',
  setextHeadingText: 'setextHeadingText',
  strong: 'strong',
  strongSequence: 'strongSequence',
  strongText: 'strongText',
  summary: 'summary',
  tagName: 'tagName',
  tagNameIdentifier: 'tagNameIdentifier',
  tagNameMarker: 'tagNameMarker',
  thematicBreak: 'thematicBreak',
  thematicBreakSequence: 'thematicBreakSequence',
  whitespace: 'whitespace'
} as const

export default tt
